### ISSUE TITLE
--disable-encryption not working anymore

### ISSUE THREAD

**Issue by crazy-max** [ungoogled-software/ungoogled-chromium-windows#36]
Hi,

There is currently an issue with the patch to disable encryption to allow portability (Eloston/ungoogled-chromium#591) on Windows. Looks like this regression occurs between Chromium 76.0.3809.132 to Chromium 77.0.3865.75 (see https://github.com/brave/brave-core/pull/3385#issuecomment-545787343). Do you have any idea about this @tangalbert919 @Eloston? I would like to fix this on Brave And ungoogled-chromium but hard to find something relevant. I have this output when I open ungoogled-chromium if `--disable-encryption` is enabled:

```
[1896:2800:0323/163555.011:ERROR:os_crypt_win.cc(102)] Failed to decrypt: Clé non valide pour l’utilisation dans l’état spécifié. (0x8009000B)
```

Thanks

**Comment by tangalbert919** [comment]
This issue should be closed if it is already fixed.

**Comment by Eloston** [comment]
Is this fixed? This issue is over a year old. I'm also struggling to recall the details of this feature, so I'm not sure how to properly test if it is still working.

**Comment by jiangzhenjerry** [comment]
No, this issue still exists. Please refer to the details [https://github.com/Eloston/ungoogled-chromium/issues/1239](here). #1239

**Comment by raisehero** [comment]
This has yet to be fixed in 
![image](https://user-images.githubusercontent.com/71166028/131238310-edd5a62c-bacc-4e0e-b6cf-47a510abf4ff.png)
ungoogled-chromium 92.0.4515.159

**Comment by raisehero** [comment]
This has yet to be fixed in ungoogled-chromium 92.0.4515.159 @Eloston 
![image](https://user-images.githubusercontent.com/71166028/131238310-edd5a62c-bacc-4e0e-b6cf-47a510abf4ff.png)

**Comment by kleuter** [comment]
This problem basically leads to non-working portable version: once I disable encryption - no cookies are saved because machine id is disabled

**Comment by jiangzhenjerry** [comment]
@kleuter I cannot reproduce your problem. To me, the original issue described by OP has been resolved. I have set `---disable-encryption` and `--disable-machine-id` and my browser is perfectly portable. Successfully tested by me and a few other folks I came across at another forum.

Please note that by default, ungoogled-chromium clears cookies and website data when exiting. I would suggest that you disable such option in chrome://settings and try again.

**Comment by kleuter** [comment]
Not true, try running your 'portable' app on another machine.
https://portapps.io/app/ungoogled-chromium-portable/#known-issues

**Comment by leo-liar** [comment]
Doesn't have to even be on an different machine ... Unfortunately when using these flags even if deleting all cookies on exit is *disabled* the cookies, etc. are still lost after closing and restarting the browser.

Still happens on the most recent version of ungoogled-chromium on Windows 10.

**Comment by jiangzhenjerry** [comment]
@kleuter As I mentioned, I and a few other folks already tested across different machines. I configured my browser on a Win11 machine and then moved it to another Win10 laptop. Extensions and cookies are intact. As a user of portable applications for 10+ years, I know perfectly what "portable" means.

The build I'm using is from [winchrome](https://github.com/macchrome/winchrome/releases)

@leo-liar I don't know what you meant by "most recent version". If you are referring to the same `portapps` build that @kleuter mentioned, then it is not the most recent as it only offers chromium **97**. `winchrome` offers up to chromium **98**.

**General principle**: Main stream git repo does not maintain -- hence is not responsible for -- 3rd-party builds. `portapps` is a 3rd-party build. Therefore, if you wanted to report any issue in **this** git repo, you could (and should) have tried some other builds to if it is a universal issue, or even better, built your own executable.

**Comment by leo-liar** [comment]
I was referring to these to builds:

- [ungoogled-chromium_97.0.4692.71-1.1_windows by nifury](https://github.com/Nifury/ungoogled-chromium-binaries/releases/tag/97.0.4692.71-1)
- [Chromium v98.0.4758.80-r950365 - ungoogled by macchrome/Marmaduke](https://github.com/macchrome/winchrome/releases/tag/v98.0.4758.80-r950365-Win64)

Both show the aforementioned bug of deleting all cookies despite configured to not to do so if both disable encryption/machine-id flags are set.

It's true that apps, extensions and settings are portable but cookies are not -- as several other users already pointed out in some of the referenced issues.

**Comment by jiangzhenjerry** [comment]
@leo-liar Thanks for the info. Then I won't be able to help here, because I and my online acquaintances are using the exact same build your are using (the 2nd link you posted) and we cannot reproduce this issue. ungoogled-chromium is my daily driver, if this issue of deleting cookies exists for me, I would be mad.

The only possibility I can think of is that there is some scripts/applications which accidentally delete the cookies file, because in 98 it changes location (to be inside the `Network` folder, rather than the root `profile` folder). Other than that, sorry I cannot help further.

**Comment by leo-liar** [comment]
Ah, it's good to know that you do not have this issue while using the most recent version. I was under the impression that this bug occured in all recent (Windows) versions of ungoogled-chromium.

I don't think any script/application is messing with my profile folder. As I specify the actual profile folder via command line switch I'm not to worried about (upcoming) changes to it's default location either.

I'll try to create a fresh profile and test if this bug still occurs. #58 got me thinking that this might be related to having a rather old profile which has been kept over several versions of ungoogled-chromium (some of which may hae been buggy in regards to the aforementioned flags).

**Comment by jiangzhenjerry** [comment]
Just to clarify - I'm not saying the location of the `[profile]` folder (could be `[user-data-dir]\Default`, or `[user-data-dir]\Profile 1`, `[user-data-dir]\Profile 2`... based on your use case) is changed. I'm saying the `Cookies` file has moved. For example, prior to 97, it likely resides as `[user-data-dir]\Default\Cookies`, but after 98 it is `[user-data-dir]\Default\**Network**\Cookies`

And yes please try a new profile. That's a good first-step for trouble-shooting.

**Comment by leo-liar** [comment]
After creating a new profile and testing around (and observing that you were right - cookies and log-in states *weren't* deleted upon browser exit with a fresh profile) in the end it was just enough for me to delete the `Local State` file from my original profile folder and cookies, etc. are suddenly surviving a browser exit/restart now!

Aftwerwards I just had to reenable some flags that were configured via `chrome://flags/` menu (instead of via command line) but no other settings were lost.

(Apparently there is now a different key here `"os_crypt":{"encrypted_key":"%BASE_64_KEY%"}` in `Local State` but no other relevant changes. And I haven't tested actually moving this profile to another computer yet.)

**Comment by jiangzhenjerry** [comment]
@leo-liar I'm glad that you tested and that it turned out to work for you too. Cheers.

@Eloston I suggest to close this issue for now.

**Comment by leo-liar** [comment]
Just for completeness:
I tested using my profile on another computer which worked as well. That means that full portability (at least while using the `--disable-encryption` *and* `--disable-machine-id` flags and disabling cookie deletion in the settings) can be achieved.

Though it may be necessary to delete the `Local State` file if the used profile is already older (i.e. from a previous ungoogled-chromium version).

**Comment by kleuter** [comment]
Ok, --disable-encryption and --disable-machine-id flags work **IF used from the command line**. When used from chrome:flags - all cookies are deleted

**Comment by kleuter** [comment]
Caused by the "**Disable encryption**" flag. All works fine with only the "**Disable machine ID**" flag

**Comment by Hashnoob** [comment]
So I tried passing  --disable-encryption and --disable-machine-id flags in all sorts of ways and configurations moving between systems to test checking the database files. Nothing works.

Is there any progress on the issue I would love a truly portable chrome.

**Comment by leo-liar** [comment]
Did you pass the flags via command line or via shortcut?
And did you remove any previous existing `Local State` file?
And within the browser settings, are cookies, etc. to be kept on browser exit?

**Comment by Hashnoob** [comment]
Command line.
Yes.
Yes.

A simple test where you run:

`chrome.exe --user-data-dir=profile --disable-encryption --disable-machine-id`

Then check the "Login Data" database look in the logins table and check the password element column for saved passwords they will still be encrypted.

**Comment by alidan** [comment]
i'm trying to move to a new windows install, chrome is the last thing I need to backup, and then this issues of tieing everything to a machine was brought up. 

so here is my issue, I have 0 idea what chrome has backed up on their servers, however I have extensions that I consider required to even use chrome, imagezoomer being one of the main ones, along with a number of scripts and settings. show of taking several hundred screenshots and rebuilding if chrome doesn't restore everything, I was hoping dragging and dropping files would work, but apparently that doesn't work with chrome because of the encryption.

is there any way to use ungoogled chromium to get these files ported or am I 100% at the whims of what googled decided to backup on their end?

**Comment by leo-liar** [comment]
@Hashnoob
Have you tried this with a separate, newly created portable install?

Regarding the enrypted table values: I'm not sure that using said flags leads to unencrypted login information being stored. I think that the used encryption (maybe just some basic encoding?) will be independent of OS user accounts (and hardware) thus making it portable.

I've just checked this myself - *USER* column entries (in the `Login Data` sqlite file) are cleartext but passwords are blobs. The profile is still portable though.

**Comment by IDKZAL** [comment]
Will this be ever fixed? :/
Don't want to switch to Firefox x)

**Comment by alidan** [comment]
For me the only thing that was hard keeping me on chrome just works on firefox too, it was just never submitted to easily be installed on it, so for me i'm trying to get a portable version of firefox going because next time I want to move from one os to another I don't want to have to sit here for 2 months wondering how to deal with chromes bs.

**Comment by teeminus** [comment]
I don't know if this has been mentioned before as I did not read the complete discussion, but have you tried deleting your chromium settings folder from the disk before using the flag? Maybe there is an encrypted file present from a previous run which then failed to decrypt as no decryption key is used.

**Comment by t5mat** [comment]
With `#disable-machine-id`, `#disable-encryption` enabled, to make cookies not get lost every reset, this worked for me:

1. Backup your `chrome://flags`
2. Exit Chromium
3. Backup your profile folders (`User Data\Default`, ...)
4. Empty out `User Data`
5. Launch `chrome.exe` with `--disable-machine-id --disable-encryption`
6. Enable `chrome://flags/#disable-machine-id`, `chrome://flags/#disable-encryption`
7. Restore your backed up `chrome://flags`
8. Disable `Clear cookies and site data when you close all windows` in `chrome://settings/cookies`
9. Exit Chromium
10. Delete `User Data\Default` and restore your backed up profile folders
11. Launch Chromium as usual (no need for the flags anymore)

(am unsure if anything other than flags is stored in non-profile files in `User Data` and should be backed up as well)

Seems like Chromium's *first* launch has to be with `--disable-machine-id --disable-encryption` in order to create a state in `User Data` in which cookies do not get lost.

Hopefully this helps narrow down the issue.

**Comment by achose369** [comment]
okay, i just tested this a bit.

turns out that you should use `--user-data-dir=profile --disable-encryption --disable-machine-id` on shortcut ,in your first use before you even have a user profile if you plan to backup or use it for portable, remember to disable clear cookies on exit.

if you enable it on flags without using `--disable-encryption --disable-machine-id` on shortcut before creating profile, you might encounter cookies delete even if you disable clearing cookies on exit.

Also, dont switch off you switch off `--disable-encryption --disable-machine-id`, it will clear cookies and reset so don't remove it

**Comment by jpsoutlook** [comment]
> With `#disable-machine-id`, `#disable-encryption` enabled, to make cookies not get lost every reset, this worked for me:
> 
> (**you should backup your whole `User Data` folder before trying this**)  **_Should I enable --disable-machine-id --disable-encryption prior to backup or mac's if needed and user data otherwise the backup is encrpted?_**
> 
> 1. Backup your `chrome://flags`  **_How do you do this, the script I found no longer works..Trust issue_**
> 2. Exit Chromium
> 3. Backup your profile folders (`User Data\Default`, ...)  **_Did you also export PreferenceMACs regkey or is that not necessary to repopulate the extensions?_**
> 4. Empty out `User Data`  **_Just to confirm, leave the folder, delete everything inside correct?_**
> 5. Launch `chrome.exe` with `--disable-machine-id --disable-encryption` **_Should I define the profile folder as suggested below like this --user-data-dir=%LOCALAPPDATA%\Chromium\User Data\Default or --user-data-dir=C:\Users\JP\AppData\Local\Chromium\User Data\Default_**
> 6. Enable `chrome://flags/#disable-machine-id`, `chrome://flags/#disable-encryption`
> 7. Restore your backed up `chrome://flags`
> 8. Disable `Clear cookies and site data when you close all windows` in `chrome://settings/cookies`
> 9. Exit Chromium
> 10. Delete `User Data\Default` and restore your backed up profile folders
> 11. Launch Chromium as usual (no need for the flags anymore)  **_So after following all the steps we still have to use flags in cli as suggesed below then remove if it worked?_**
> 
> (am unsure if anything other than flags is stored in non-profile files in `User Data` and should be backed up as well)
> 
> Seems like Chromium's _first_ launch has to be with `--disable-machine-id --disable-encryption` in order to create a state in `User Data` in which cookies do not get lost.
> 
> Hopefully this helps narrow down the issue.

**Comment by rtllxndr** [comment]
I have found the same through trial and error. Need to create a new profile with options, then it works.

**Comment by mranonymous011000001** [comment]
its been long time, any one know any safe alternative that can be portable.

anyways i love this project just waiting for this to fix
